project_id = "cxvfoijklbwzzondmwuw"

[functions.suggest-salary]
verify_jwt = false

[functions.match-jobs]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.fetch-scopus]
verify_jwt = false

[functions.fetch-orcid]
verify_jwt = false
