project_id = "jclubczyyuveeqiqlwxg"

[functions.suggest-salary]
verify_jwt = false

[functions.match-jobs]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.fetch-scopus]
verify_jwt = false

[functions.fetch-orcid]
verify_jwt = false

[functions.send-recruiter-message]
verify_jwt = false

[functions.track-email-event]
verify_jwt = false

[functions.recruiter-chat]
verify_jwt = false

[functions.admin-mass-upload]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false
